// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SC.DAL.EF;

namespace SC.DAL.Migrations
{
    [DbContext(typeof(SupportCenterDbContext))]
    [Migration("20190312150959_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SC.BL.Domain.Ticket", b =>
                {
                    b.Property<int>("TicketNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<DateTime>("DateOpened");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<byte>("State");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("TicketNumber");

                    b.HasIndex("State");

                    b.ToTable("Tickets");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Ticket");
                });

            modelBuilder.Entity("SC.BL.Domain.TicketResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsClientResponse");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<int>("TicketFK");

                    b.HasKey("Id");

                    b.HasIndex("TicketFK");

                    b.ToTable("TicketResponses");
                });

            modelBuilder.Entity("SC.BL.Domain.HardwareTicket", b =>
                {
                    b.HasBaseType("SC.BL.Domain.Ticket");

                    b.Property<string>("DeviceName");

                    b.HasDiscriminator().HasValue("HardwareTicket");
                });

            modelBuilder.Entity("SC.BL.Domain.TicketResponse", b =>
                {
                    b.HasOne("SC.BL.Domain.Ticket", "Ticket")
                        .WithMany("Responses")
                        .HasForeignKey("TicketFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
